// <auto-generated />
using System;
using Iot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Iot.Data.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Primary network server for the demo site",
                            Name = "Main NET Server",
                            ParentDeviceId = 0,
                            Status = "Online",
                            TypeId = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Local nano controller handling plant room IO",
                            Name = "Nano Controller 1",
                            ParentDeviceId = 1,
                            Status = "Online",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wireless LoRa gateway for remote sensors",
                            Name = "LoRa Gateway",
                            ParentDeviceId = 1,
                            Status = "Warning",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Client display for local operators",
                            Name = "Operator Panel",
                            ParentDeviceId = 2,
                            Status = "Online",
                            TypeId = 3
                        });
                });

            modelBuilder.Entity("Iot.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Points used to monitor and control plant room equipment",
                            Name = "Plant Room"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wireless sensor points reported through the LoRa gateway",
                            Name = "Remote Sensors"
                        });
                });

            modelBuilder.Entity("Iot.Data.Models.GroupPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("GroupId", "PointId")
                        .IsUnique();

                    b.ToTable("GroupPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            PointId = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            PointId = 2
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 1,
                            PointId = 4
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 2,
                            PointId = 3
                        });
                });

            modelBuilder.Entity("Iot.Data.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("RawStatus")
                        .HasColumnType("REAL");

                    b.Property<double>("Scale")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status0")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "DI:1",
                            Description = "Digital input showing the pump run state",
                            DeviceId = 2,
                            Name = "Pump Run Feedback",
                            RawStatus = 1.0,
                            Scale = 1.0,
                            Status = "On",
                            Status0 = "Stopped",
                            Status1 = "Running",
                            TimeStamp = new DateTime(2026, 4, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            TypeId = 0,
                            Units = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "DO:1",
                            Description = "Digital output command for pump start",
                            DeviceId = 2,
                            Name = "Pump Command",
                            RawStatus = 1.0,
                            Scale = 1.0,
                            Status = "On",
                            Status0 = "Off",
                            Status1 = "On",
                            TimeStamp = new DateTime(2026, 4, 24, 8, 0, 5, 0, DateTimeKind.Utc),
                            TypeId = 1,
                            Units = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "AI:1",
                            Description = "Analog tank level from remote sensor",
                            DeviceId = 3,
                            Name = "Tank Level",
                            RawStatus = 684.0,
                            Scale = 0.10000000000000001,
                            Status = "68.4",
                            Status0 = "Low",
                            Status1 = "High",
                            TimeStamp = new DateTime(2026, 4, 24, 8, 1, 0, 0, DateTimeKind.Utc),
                            TypeId = 2,
                            Units = "%"
                        },
                        new
                        {
                            Id = 4,
                            Address = "AO:1",
                            Description = "Analog output controlling valve opening",
                            DeviceId = 2,
                            Name = "Valve Position",
                            RawStatus = 450.0,
                            Scale = 0.10000000000000001,
                            Status = "45.0",
                            Status0 = "Closed",
                            Status1 = "Open",
                            TimeStamp = new DateTime(2026, 4, 24, 8, 1, 30, 0, DateTimeKind.Utc),
                            TypeId = 3,
                            Units = "%"
                        });
                });

            modelBuilder.Entity("Iot.Data.Models.GroupPoint", b =>
                {
                    b.HasOne("Iot.Data.Models.Group", "Group")
                        .WithMany("GroupPoints")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iot.Data.Models.Point", "Point")
                        .WithMany("GroupPoints")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("Iot.Data.Models.Point", b =>
                {
                    b.HasOne("Iot.Data.Models.Device", "Device")
                        .WithMany("Points")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Iot.Data.Models.Device", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Iot.Data.Models.Group", b =>
                {
                    b.Navigation("GroupPoints");
                });

            modelBuilder.Entity("Iot.Data.Models.Point", b =>
                {
                    b.Navigation("GroupPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
