; PlatformIO Project Configuration File

[platformio]
default_envs = lora1

[env]
platform = espressif32
framework = arduino
board = ttgo-lora32-v2
board_build.mcu = esp32
monitor_speed = 115200
build_src_filter =
	+<main.cpp>
	+<LoRa.cpp>
lib_deps =
	bblanchon/ArduinoJson@^7.4.2
build_flags =
	-D IOT_WIFI_SSID=\"OPPO\ A52\"
	-D IOT_WIFI_PASSWORD=\"\"
	-D IOT_UPSTREAM_HOST=\"pi51\"
	-D IOT_UPSTREAM_PORT=5050

[env:lora1]
build_flags =
	${env.build_flags}
	-D IOT_PEER_NAME=\"lora1\"
	-D IOT_DEVICE_ID=11
	-D IOT_ENABLE_WIFI=1

[env:lora2]
build_flags =
	${env.build_flags}
	-D IOT_PEER_NAME=\"lora2\"
	-D IOT_DEVICE_ID=12
	-D IOT_ENABLE_WIFI=0
